# Generated by Django 5.2.3 on 2025-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
